version: '3'

services:
  web:
    build: .
    command: bash -c "pipenv install --system && python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    expose: 
      - 8000
    tty: True
    stdin_open: True
  
  db:
    image: postgres:11
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'  

  nginx:
      build: 
          context: .
          dockerfile: ./nginx/Dockerfile
      ports:
          - 80:80
      depends_on:
          - web
